/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as mainRouteRouteImport } from './routes/(main)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicAuthRouteImport } from './routes/(public)/auth'
import { Route as mainProfileIndexRouteImport } from './routes/(main)/profile/index'
import { Route as mainJobsIndexRouteImport } from './routes/(main)/jobs/index'
import { Route as mainFreelancersIndexRouteImport } from './routes/(main)/freelancers/index'
import { Route as mainDashboardIndexRouteImport } from './routes/(main)/dashboard/index'
import { Route as mainJobsCreateIndexRouteImport } from './routes/(main)/jobs/create/index'
import { Route as mainJobsIdIndexRouteImport } from './routes/(main)/jobs/$id/index'
import { Route as mainJobsIdMilestonesIndexRouteImport } from './routes/(main)/jobs/$id/milestones/index'

const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicAuthRoute = publicAuthRouteImport.update({
  id: '/(public)/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const mainProfileIndexRoute = mainProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainJobsIndexRoute = mainJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainFreelancersIndexRoute = mainFreelancersIndexRouteImport.update({
  id: '/freelancers/',
  path: '/freelancers/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainDashboardIndexRoute = mainDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainJobsCreateIndexRoute = mainJobsCreateIndexRouteImport.update({
  id: '/jobs/create/',
  path: '/jobs/create/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainJobsIdIndexRoute = mainJobsIdIndexRouteImport.update({
  id: '/jobs/$id/',
  path: '/jobs/$id/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainJobsIdMilestonesIndexRoute =
  mainJobsIdMilestonesIndexRouteImport.update({
    id: '/jobs/$id/milestones/',
    path: '/jobs/$id/milestones/',
    getParentRoute: () => mainRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof publicAuthRoute
  '/': typeof publicIndexRoute
  '/dashboard': typeof mainDashboardIndexRoute
  '/freelancers': typeof mainFreelancersIndexRoute
  '/jobs': typeof mainJobsIndexRoute
  '/profile': typeof mainProfileIndexRoute
  '/jobs/$id': typeof mainJobsIdIndexRoute
  '/jobs/create': typeof mainJobsCreateIndexRoute
  '/jobs/$id/milestones': typeof mainJobsIdMilestonesIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof publicAuthRoute
  '/': typeof publicIndexRoute
  '/dashboard': typeof mainDashboardIndexRoute
  '/freelancers': typeof mainFreelancersIndexRoute
  '/jobs': typeof mainJobsIndexRoute
  '/profile': typeof mainProfileIndexRoute
  '/jobs/$id': typeof mainJobsIdIndexRoute
  '/jobs/create': typeof mainJobsCreateIndexRoute
  '/jobs/$id/milestones': typeof mainJobsIdMilestonesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(main)': typeof mainRouteRouteWithChildren
  '/(public)/auth': typeof publicAuthRoute
  '/(public)/': typeof publicIndexRoute
  '/(main)/dashboard/': typeof mainDashboardIndexRoute
  '/(main)/freelancers/': typeof mainFreelancersIndexRoute
  '/(main)/jobs/': typeof mainJobsIndexRoute
  '/(main)/profile/': typeof mainProfileIndexRoute
  '/(main)/jobs/$id/': typeof mainJobsIdIndexRoute
  '/(main)/jobs/create/': typeof mainJobsCreateIndexRoute
  '/(main)/jobs/$id/milestones/': typeof mainJobsIdMilestonesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/'
    | '/dashboard'
    | '/freelancers'
    | '/jobs'
    | '/profile'
    | '/jobs/$id'
    | '/jobs/create'
    | '/jobs/$id/milestones'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/'
    | '/dashboard'
    | '/freelancers'
    | '/jobs'
    | '/profile'
    | '/jobs/$id'
    | '/jobs/create'
    | '/jobs/$id/milestones'
  id:
    | '__root__'
    | '/(main)'
    | '/(public)/auth'
    | '/(public)/'
    | '/(main)/dashboard/'
    | '/(main)/freelancers/'
    | '/(main)/jobs/'
    | '/(main)/profile/'
    | '/(main)/jobs/$id/'
    | '/(main)/jobs/create/'
    | '/(main)/jobs/$id/milestones/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  mainRouteRoute: typeof mainRouteRouteWithChildren
  publicAuthRoute: typeof publicAuthRoute
  publicIndexRoute: typeof publicIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(main)': {
      id: '/(main)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/auth': {
      id: '/(public)/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof publicAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/profile/': {
      id: '/(main)/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof mainProfileIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/jobs/': {
      id: '/(main)/jobs/'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof mainJobsIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/freelancers/': {
      id: '/(main)/freelancers/'
      path: '/freelancers'
      fullPath: '/freelancers'
      preLoaderRoute: typeof mainFreelancersIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/dashboard/': {
      id: '/(main)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof mainDashboardIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/jobs/create/': {
      id: '/(main)/jobs/create/'
      path: '/jobs/create'
      fullPath: '/jobs/create'
      preLoaderRoute: typeof mainJobsCreateIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/jobs/$id/': {
      id: '/(main)/jobs/$id/'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof mainJobsIdIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/jobs/$id/milestones/': {
      id: '/(main)/jobs/$id/milestones/'
      path: '/jobs/$id/milestones'
      fullPath: '/jobs/$id/milestones'
      preLoaderRoute: typeof mainJobsIdMilestonesIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
  }
}

interface mainRouteRouteChildren {
  mainDashboardIndexRoute: typeof mainDashboardIndexRoute
  mainFreelancersIndexRoute: typeof mainFreelancersIndexRoute
  mainJobsIndexRoute: typeof mainJobsIndexRoute
  mainProfileIndexRoute: typeof mainProfileIndexRoute
  mainJobsIdIndexRoute: typeof mainJobsIdIndexRoute
  mainJobsCreateIndexRoute: typeof mainJobsCreateIndexRoute
  mainJobsIdMilestonesIndexRoute: typeof mainJobsIdMilestonesIndexRoute
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainDashboardIndexRoute: mainDashboardIndexRoute,
  mainFreelancersIndexRoute: mainFreelancersIndexRoute,
  mainJobsIndexRoute: mainJobsIndexRoute,
  mainProfileIndexRoute: mainProfileIndexRoute,
  mainJobsIdIndexRoute: mainJobsIdIndexRoute,
  mainJobsCreateIndexRoute: mainJobsCreateIndexRoute,
  mainJobsIdMilestonesIndexRoute: mainJobsIdMilestonesIndexRoute,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  mainRouteRoute: mainRouteRouteWithChildren,
  publicAuthRoute: publicAuthRoute,
  publicIndexRoute: publicIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
